[package]
name = "fixture-io"
version = "0.1.0"
authors = ["Carl Lerche <me@carllerche.com>"]

[dependencies]
futures = "0.1"
tokio-io = "0.1"
tokio-timer = "0.1"
bytes = "0.4"
io-dump = { git = "https://github.com/carllerche/io-dump" }
